/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BaseResponseString } from '../../models'

import { MyAxios } from '../../../utils/request'

export const healthCheck = () => {
  return MyAxios<BaseResponseString>({ url: `/health/`, method: 'GET' })
}
export type HealthCheckResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>
