/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AppAddRequest,
  AppDeployRequest,
  AppQueryRequest,
  AppUpdateMyRequest,
  AppUpdateRequest,
  BaseResponseApp,
  BaseResponseAppVO,
  BaseResponseBoolean,
  BaseResponseLong,
  BaseResponsePageAppVO,
  BaseResponseString,
  ChatToGenCodeParams,
  DeleteRequest,
  GetAppByIdParams,
  GetMyAppByIdParams,
  ServerSentEventString,
} from '../models'

import { MyAxios } from '@/utils/request'

export const updateApp = (appUpdateRequest: AppUpdateRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/app/update`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appUpdateRequest,
  })
}
export const updateMyApp = (appUpdateMyRequest: AppUpdateMyRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/app/update/my`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appUpdateMyRequest,
  })
}
export const listAppVOByPage = (appQueryRequest: AppQueryRequest) => {
  return MyAxios<BaseResponsePageAppVO>({
    url: `/app/list/page/vo`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appQueryRequest,
  })
}
export const listMyAppVOByPage = (appQueryRequest: AppQueryRequest) => {
  return MyAxios<BaseResponsePageAppVO>({
    url: `/app/list/my/page/vo`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appQueryRequest,
  })
}
export const listGoodAppVOByPage = (appQueryRequest: AppQueryRequest) => {
  return MyAxios<BaseResponsePageAppVO>({
    url: `/app/good/list/page/vo`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appQueryRequest,
  })
}
export const deployApp = (appDeployRequest: AppDeployRequest) => {
  return MyAxios<BaseResponseString>({
    url: `/app/deploy`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appDeployRequest,
  })
}
export const deleteApp = (deleteRequest: DeleteRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/app/delete`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: deleteRequest,
  })
}
export const deleteMyApp = (deleteRequest: DeleteRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/app/delete/my`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: deleteRequest,
  })
}
export const addApp = (appAddRequest: AppAddRequest) => {
  return MyAxios<BaseResponseLong>({
    url: `/app/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: appAddRequest,
  })
}
export const getAppById = (params: GetAppByIdParams) => {
  return MyAxios<BaseResponseApp>({ url: `/app/get`, method: 'GET', params })
}
export const getMyAppById = (params: GetMyAppByIdParams) => {
  return MyAxios<BaseResponseAppVO>({
    url: `/app/get/my`,
    method: 'GET',
    params,
  })
}
export const chatToGenCode = (params: ChatToGenCodeParams) => {
  return MyAxios<ServerSentEventString[]>({
    url: `/app/chat/gen/code`,
    method: 'GET',
    params,
  })
}
export type UpdateAppResult = NonNullable<Awaited<ReturnType<typeof updateApp>>>
export type UpdateMyAppResult = NonNullable<
  Awaited<ReturnType<typeof updateMyApp>>
>
export type ListAppVOByPageResult = NonNullable<
  Awaited<ReturnType<typeof listAppVOByPage>>
>
export type ListMyAppVOByPageResult = NonNullable<
  Awaited<ReturnType<typeof listMyAppVOByPage>>
>
export type ListGoodAppVOByPageResult = NonNullable<
  Awaited<ReturnType<typeof listGoodAppVOByPage>>
>
export type DeployAppResult = NonNullable<Awaited<ReturnType<typeof deployApp>>>
export type DeleteAppResult = NonNullable<Awaited<ReturnType<typeof deleteApp>>>
export type DeleteMyAppResult = NonNullable<
  Awaited<ReturnType<typeof deleteMyApp>>
>
export type AddAppResult = NonNullable<Awaited<ReturnType<typeof addApp>>>
export type GetAppByIdResult = NonNullable<
  Awaited<ReturnType<typeof getAppById>>
>
export type GetMyAppByIdResult = NonNullable<
  Awaited<ReturnType<typeof getMyAppById>>
>
export type ChatToGenCodeResult = NonNullable<
  Awaited<ReturnType<typeof chatToGenCode>>
>
