/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { MyAxios } from '@/utils/request'

export const serveStaticResource = (deployKey: string) => {
  return MyAxios<Blob>({ url: `/static/${deployKey}/**`, method: 'GET' })
}
export type ServeStaticResourceResult = NonNullable<
  Awaited<ReturnType<typeof serveStaticResource>>
>
