/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  BaseResponseBoolean,
  BaseResponseLoginUserVO,
  BaseResponseLong,
  BaseResponsePageUserVO,
  BaseResponseUser,
  BaseResponseUserVO,
  DeleteRequest,
  GetUserByIdParams,
  GetUserVOByIdParams,
  UserAddRequest,
  UserLoginRequest,
  UserQueryRequest,
  UserRegisterRequest,
  UserUpdateRequest,
} from '../models'

import { MyAxios } from '@/utils/request'

export const updateUser = (userUpdateRequest: UserUpdateRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/user/update`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userUpdateRequest,
  })
}

export const register = (userRegisterRequest: UserRegisterRequest) => {
  return MyAxios<BaseResponseLong>({
    url: `/user/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userRegisterRequest,
  })
}
export const userLogout = () => {
  return MyAxios<BaseResponseBoolean>({ url: `/user/logout`, method: 'POST' })
}

export const userLogin = (userLoginRequest: UserLoginRequest) => {
  return MyAxios<BaseResponseLoginUserVO>({
    url: `/user/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userLoginRequest,
  })
}

export const listUserVOByPage = (userQueryRequest: UserQueryRequest) => {
  return MyAxios<BaseResponsePageUserVO>({
    url: `/user/list/page/vo`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userQueryRequest,
  })
}

export const getLoginUser = () => {
  return MyAxios<BaseResponseLoginUserVO>({
    url: `/user/get/login`,
    method: 'POST',
  })
}

export const deleteUser = (deleteRequest: DeleteRequest) => {
  return MyAxios<BaseResponseBoolean>({
    url: `/user/delete`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: deleteRequest,
  })
}

export const addUser = (userAddRequest: UserAddRequest) => {
  return MyAxios<BaseResponseLong>({
    url: `/user/add`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: userAddRequest,
  })
}

export const getUserById = (params: GetUserByIdParams) => {
  return MyAxios<BaseResponseUser>({ url: `/user/get`, method: 'GET', params })
}

export const getUserVOById = (params: GetUserVOByIdParams) => {
  return MyAxios<BaseResponseUserVO>({
    url: `/user/get/vo`,
    method: 'GET',
    params,
  })
}

export type UpdateUserResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type UserLogoutResult = NonNullable<
  Awaited<ReturnType<typeof userLogout>>
>
export type UserLoginResult = NonNullable<Awaited<ReturnType<typeof userLogin>>>
export type ListUserVOByPageResult = NonNullable<
  Awaited<ReturnType<typeof listUserVOByPage>>
>
export type GetLoginUserResult = NonNullable<
  Awaited<ReturnType<typeof getLoginUser>>
>
export type DeleteUserResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>
export type AddUserResult = NonNullable<Awaited<ReturnType<typeof addUser>>>
export type GetUserByIdResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>
export type GetUserVOByIdResult = NonNullable<
  Awaited<ReturnType<typeof getUserVOById>>
>
