/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AppQueryRequest {
  pageNum?: number
  pageSize?: number
  sortField?: string
  sortOrder?: string
  id?: number
  appName?: string
  cover?: string
  initPrompt?: string
  priority?: number
  codeGenType?: string
  deployKey?: string
  userId?: number
}
