/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AppUpdateRequest {
  id?: number
  appName?: string
  cover?: string
  priority?: number
}
