/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user'

export interface BaseResponseUser {
  code?: number
  data?: User
  message?: string
}
