/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageAppVO } from './pageAppVO'

export interface BaseResponsePageAppVO {
  code?: number
  data?: PageAppVO
  message?: string
}
