/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageUserVO } from './pageUserVO'

export interface BaseResponsePageUserVO {
  code?: number
  data?: PageUserVO
  message?: string
}
