/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AppVO } from './appVO'

export interface BaseResponseAppVO {
  code?: number
  data?: AppVO
  message?: string
}
