/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserVO } from './userVO'

export interface BaseResponseUserVO {
  code?: number
  data?: UserVO
  message?: string
}
