/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginUserVO } from './loginUserVO'

export interface BaseResponseLoginUserVO {
  code?: number
  data?: LoginUserVO
  message?: string
}
