/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserVO } from './userVO'

export interface PageUserVO {
  records?: UserVO[]
  pageNumber?: number
  pageSize?: number
  totalPage?: number
  totalRow?: number
  optimizeCountQuery?: boolean
}
