/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserAddRequest {
  userName?: string
  userAccount?: string
  userAvatar?: string
  userProfile?: string
  userRole?: string
}
