/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface User {
  id?: number
  userAccount?: string
  userPassword?: string
  userName?: string
  userAvatar?: string
  userProfile?: string
  userRole?: string
  editTime?: string
  createTime?: string
  updateTime?: string
  isDelete?: number
}
