/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserRegisterRequest {
  userAccount?: string
  userPassword?: string
  checkPassword?: string
}
