/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserQueryRequest {
  pageNum?: number
  pageSize?: number
  sortField?: string
  sortOrder?: string
  id?: number
  userName?: string
  userAccount?: string
  userProfile?: string
  userRole?: string
}
